import Foundation

extension BashSession {
    func registerDefaultCommands() async {
        let defaults: [any BuiltinCommand.Type] = [
            CatCommand.self,
            CpCommand.self,
            LnCommand.self,
            LsCommand.self,
            MkdirCommand.self,
            MvCommand.self,
            ReadlinkCommand.self,
            RmCommand.self,
            RmdirCommand.self,
            StatCommand.self,
            TouchCommand.self,
            ChmodCommand.self,
            FileCommand.self,
            TreeCommand.self,
            DiffCommand.self,
            GrepCommand.self,
            RgCommand.self,
            HeadCommand.self,
            TailCommand.self,
            WcCommand.self,
            SortCommand.self,
            UniqCommand.self,
            CutCommand.self,
            TrCommand.self,
            AwkCommand.self,
            SedCommand.self,
            XargsCommand.self,
            PrintfCommand.self,
            Base64Command.self,
            Sha256sumCommand.self,
            Sha1sumCommand.self,
            Md5sumCommand.self,
            GzipCommand.self,
            GunzipCommand.self,
            ZcatCommand.self,
            ZipCommand.self,
            UnzipCommand.self,
            TarCommand.self,
            JqCommand.self,
            YqCommand.self,
            XanCommand.self,
            BasenameCommand.self,
            CdCommand.self,
            DirnameCommand.self,
            DuCommand.self,
            EchoCommand.self,
            EnvCommand.self,
            ExportCommand.self,
            FindCommand.self,
            PrintenvCommand.self,
            PwdCommand.self,
            TeeCommand.self,
            CurlCommand.self,
            WgetCommand.self,
            HtmlToMarkdownCommand.self,
            ClearCommand.self,
            DateCommand.self,
            HostnameCommand.self,
            FalseCommand.self,
            WhoamiCommand.self,
            HelpCommand.self,
            HistoryCommand.self,
            JobsCommand.self,
            FgCommand.self,
            WaitCommand.self,
            PsCommand.self,
            KillCommand.self,
            SeqCommand.self,
            SleepCommand.self,
            TimeCommand.self,
            TimeoutCommand.self,
            TrueCommand.self,
            WhichCommand.self,
        ]

        for command in defaults {
            await register(command)
        }
    }
}
